set schema 'BIT_HACK';

CREATE TABLE ROLE (
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE USERS (
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FOREIGN KEY (ROLE_NAME) REFERENCES ROLE(NAME)
);

INSERT INTO ROLE (NAME)
VALUES
    ('ROLE_APPLICANT'),
    ('ROLE_CITY_SERVICE'),
    ('ROLE_JANITOR'),
    ('ROLE_MAYOR');
