version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:16-bookworm
    environment:
      - POSTGRES_DB=bithack
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    privileged: true
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - "minio-data:/data"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /bitnami/minio/data --console-address ":9001"

volumes:
  pgdata:
  minio-data:

networks:
  default: